sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6hc33zTmoF8p7FXEzW
    access-key-secret: h0SEMb1cV4a18qWKlzlIV4vmuJ3RaH
    bucket-name: take-out-bo
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10


  wechat:
    appid: wx48497d083d72c85a
    secret: 1000a8088234fdb01668da8d8521e228

